// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import "github.com/stretchr/testify/mock"
import "github.com/Shopify/sarama"

// OffsetManager is an autogenerated mock type for the OffsetManager type
type OffsetManager struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *OffsetManager) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ManagePartition provides a mock function with given fields: topic, partition
func (_m *OffsetManager) ManagePartition(topic string, partition int32) (sarama.PartitionOffsetManager, error) {
	ret := _m.Called(topic, partition)

	var r0 sarama.PartitionOffsetManager
	if rf, ok := ret.Get(0).(func(string, int32) sarama.PartitionOffsetManager); ok {
		r0 = rf(topic, partition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sarama.PartitionOffsetManager)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int32) error); ok {
		r1 = rf(topic, partition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
